class LabelGenerator:
    """
    Generates user-facing transparency labels based on combined score and confidence.
    """
    @staticmethod
    def generate(combined_prob, confidence):
        confidence_pct = int(confidence * 100)
        
        # Threshold for high-confidence classification is 0.40 confidence
        # (corresponds to combined probability <= 0.30 or >= 0.70)
        if confidence < 0.40:
            return {
                "attribution_result": "uncertain",
                "status": "Uncertain / Mixed Attribution",
                "description": f"Attribution analysis is uncertain (confidence: {confidence_pct}%). The text displays a mixture of stylistic patterns, such as human-like vocabulary diversity combined with structured sentence variance, making it inconclusive to attribute to either human or AI.",
                "badge_color": "yellow"
            }
        
        if combined_prob >= 0.5:
            return {
                "attribution_result": "human",
                "status": "High-Confidence Human",
                "description": f"Attribution analysis indicates with high confidence ({confidence_pct}%) that this text was written by a human. The content displays natural linguistic flow, high sentence length variance, and vocabulary patterns typical of human writing.",
                "badge_color": "green"
            }
        else:
            return {
                "attribution_result": "ai",
                "status": "High-Confidence AI",
                "description": f"Attribution analysis indicates with high confidence ({confidence_pct}%) that this text was generated by an artificial intelligence model. The content features highly uniform sentence lengths and predictable word choices consistent with machine-generated prose.",
                "badge_color": "red"
            }

